---
- name: Prepare and Install MISP on Ubuntu 24.04 and Import Threat Events
  hosts: misp
  become: yes
  gather_facts: false
    
  vars:
    misp_app_path: "/var/www/MISP"
    local_event_files:
      - "MISP_Event_2025_Medusa.json"
      - "MISP_Event_2025_XorDDoS.json"
      - "MISP_Event_2025_MustangPanda.json"
    remote_event_dir: "/tmp/misp_events"
    
  pre_tasks:
    - name: Install Python 3 and python3-apt (required for Ansible)
      raw: |
        apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-apt
      changed_when: false
      
    - name: Gather facts (after Python is installed)
      setup:
    
  tasks:
    - name: Ensure base packages are installed
      apt:
        name: 
          - git
          - curl
          - sudo
        update_cache: yes
        
    - name: Remove previous MISP repo if it exists
      file:
        path: /opt/MISP
        state: absent
        
    - name: Clone MISP repo (use default branch)
      git:
        repo: https://github.com/MISP/MISP.git
        dest: /opt/MISP
        update: yes
        force: yes
        
    - name: Run MISP install script for Ubuntu 24.04
      command: bash /opt/MISP/INSTALL/INSTALL.ubuntu2404.sh
      args:
        chdir: /opt/MISP/INSTALL
        
    - name: Fetch MISP settings (with admin password)
      slurp:
        src: /var/log/misp_settings.txt
      register: misp_settings
      
    - name: Save MISP settings locally
      copy:
        content: "{{ misp_settings.content | b64decode }}"
        dest: "./misp-settings.txt"
        mode: '0600'
      delegate_to: localhost
      
    - name: Ensure remote event directory exists
      file:
        path: "{{ remote_event_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        
    - name: Copy MISP event JSON files to server
      copy:
        src: "{{ item }}"
        dest: "{{ remote_event_dir }}/{{ item }}"
        owner: www-data
        group: www-data
        mode: '0644'
      loop: "{{ local_event_files }}"
      
    - name: Import MISP events via CLI
      command: php app/Console/cake event import {{ remote_event_dir }}/{{ item }}
      args:
        chdir: "{{ misp_app_path }}"
      become_user: www-data
      loop: "{{ local_event_files }}"
      
    - name: Optionally clean up JSON files from remote server
      file:
        path: "{{ remote_event_dir }}"
        state: absent